---
# tasks file for snapclient
- name: "Ensure the Snapcast client is installed"
  become: true
  apt:
    deb: "https://github.com/badaix/snapcast/releases/download/v{{ snapcast_version }}/snapclient_{{ snapcast_version }}{{ snapcast_version_suffix }}_{{ snapcast_architecture}}.deb"
- name: "Ensure /var/lib/snapclient exists (to prevent runtime warnings)"
  become: true
  file:
    path: /var/lib/snapclient
    state: directory
    owner: "{{ snapcast_client_user }}"
    group: audio
    mode: 0755

- name: Disable default config
  become: yes
  systemd:
    name: snapclient
    state: stopped
    enabled: no

- name: "Ensure the snapclient user has a shell set. If it hasn't, the client won't play audio properly. See https://github.com/badaix/snapcast/issues/229#issuecomment-328167681."
  become: true
  lineinfile:
    path: /etc/passwd
    regexp: "^snapclient:(.*):/var/lib/snapclient:$"
    line: "snapclient:\\1:/var/lib/snapclient:/usr/sbin/nologin"
    backrefs: true

- name: Create systemd unit files
  become: true
  tags:
    - multi
  with_dict: "{{ snapcast_client_daemon_options }}"
  register: unit
  copy:
    dest: /lib/systemd/system/snapclient-{{ item.key }}.service
    content: |
      [Unit]
      Description=Snapcast client {{ item.key }}
      Documentation=man:snapclient(1)
      Wants=avahi-daemon.service
      After=network-online.target time-sync.target sound.target avahi-daemon.service

      [Service]
      EnvironmentFile=-/etc/default/snapclient-{{ item.key }}
      ExecStart=/usr/bin/snapclient --logsink=system $SNAPCLIENT_OPTS
      User={{ snapcast_client_user }}
      Group=audio
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

- name: Ensure the options to the Snapclient daemon are set
  become: true
  tags:
    - multi
  with_dict: "{{ snapcast_client_daemon_options }}"
  register: conf
  copy:
    dest: /etc/default/snapclient-{{ item.key }}
    content: |
      START_SNAPCLIENT=true
      SNAPCLIENT_OPTS="{{ item.value }}"

- name: Ensure system level volume
  become: yes
  when: (snapcast_client_volume_cmd or '')|length > 0
  changed_when: no
  shell:
    cmd: "{{ snapcast_client_volume_cmd }}"

- name: Install/reloads system services
  with_dict: "{{ snapcast_client_daemon_options }}"
  tags:
    - multi
  become: yes
  systemd:
    name: snapclient-{{ item.key }}
    state: "{{ 'restarted' if conf.changed or unit.changed else 'started' }}"
    enabled: yes
    daemon_reload: "{{ conf.changed or unit.changed }}"
