---
# tasks file for snapcast
- include: common.yml
  when:
    - snapcast_install_server == true or snapcast_install_client == true
- include: server.yml
  when:
    - snapcast_install_server == true
- include_tasks: client.yml
  when:
    - snapcast_install_client == true
  tags:
    - multi
